theme: minima
title: "Guia do Comprador"
tagline: "Comparativos honestos e análises técnicas diretas ao ponto"
description: "Comparativos técnicos diretos e análises de produtos para ajudar você a decidir a melhor compra com o melhor preço."
lang: "pt-BR"
timezone: "America/Sao_Paulo"
url: "https://wstorres.github.io"
baseurl: "/guiadocomprador"
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author: "Redação Guia do Comprador"
email: "contato@guiadocomprador.com"
google_analytics: "G-KDM98J519E"